credentials:
  usernames:
    nithin:
      email: nitin@gmail.com
      name: nithin
      password: abc
    pramod:
      email: pramod@gmail.com
      name:  pramod
      password:  abc
cookie:
  expiry_days: 30
  key: random_signature_key # Must be string
  name: random_cookie_name
